[package]
name = "yo-tui"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
emojis = "=0.9.0"
icu_properties = { version = "=2.2.0", features = ["compiled_data"] }
unicode-segmentation = "=1.13.3"
yo-core = { path = "../yo-core" }

[target.'cfg(unix)'.dependencies]
crossterm = { version = "=0.29.0", default-features = false, features = ["bracketed-paste", "event-stream", "events"] }
futures-core = "=0.3.33"
rustix = { version = "=1.1.4", default-features = false, features = ["std", "stdio", "termios"] }

[lints]
workspace = true
