[package]
name = "yo-backend-managed"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
yo-backend = { path = "../foundation" }
yo-core = { path = "../../yo-core" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[lints]
workspace = true
